### ISSUE TITLE
NOT ABLE TO VERIFY ON BSCSCAN 

### ISSUE THREAD

**Issue by Eloonpooch** [CoryITpro/MAMATOKEN-BEP20Token#1]
Hi Dev thank you very much for this amazing code . I have deployed the code on Binance chain but i am not able to verify the code . please help

**Comment by CoryITpro** [comment]
Hi. Nice to hear from you.

MAMATOKEN is a bep20 token and it has to be deployed on Binance Smart Chain.

If you have any questions, then please contact me on skype or discord.
Thank you.

Skype: live:.cid.b64830812c410bb4
Discord: Cory K.#1728

**Comment by Eloonpooch** [comment]
Thanks for the reply Sir . Do you have Telegram Dev ? I never used skype or Discord

**Comment by CoryITpro** [comment]
Sorry, I don't like Telegram so I don't use it. Do you use slack?

**Comment by k1ng1337** [comment]
can you send new discord name? i cant add you

**Comment by rebelholic** [comment]
@CoryITpro can you send new discord name? i cant add you

**Comment by CoryITpro** [comment]
Hello

My discord name is The Notorious#0001

Thanks

**Comment by CoryITpro** [comment]
Or @CoryITpro on telegram
