### ISSUE TITLE
Wallet Marketing and Wallet charity receive nothing

### ISSUE THREAD

**Issue by dkjeune** [CoryITpro/MAMATOKEN-BEP20Token#2]
Hi, can you help me ?

**Comment by dkjeune** [comment]
Also, no liquidity add.
Thanks for your help.

**Comment by CoryITpro** [comment]
Hi. Do you have discord? or skype?
Did you test it on bsctestnet?

**Comment by dkjeune** [comment]
Hi, yes i have a discord
https://discord.gg/DSNewy5S

**Comment by dkjeune** [comment]
yes i test it on bsc testnet

**Comment by CoryITpro** [comment]
Then please test the token on the kovan testnet.
Bsc testnet doesn't support pairing well.

**Comment by CoryITpro** [comment]
Current code base is for Kovan testnet.
